version: '3.8'

services:
  # Backend API Service with Frontend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stonx
    ports:
      - "6969:6969"
    volumes:
      - stonx-data:/app/data
      - stonx-logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=6969
      - DATABASE_URL=file:/app/data/stonx.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  stonx-data:
    driver: local
  stonx-logs:
    driver: local 